apisix:
  node_listen: 9080
  enable_admin: true
  admin_listen:
    ip: 0.0.0.0
    port: 9180
  
  etcd:
    host:
      - "http://etcd:2379"    # Nombre del servicio en docker-compose
  
  admin_key:
    - name: "admin"
      key: "dhOXJMgujARZCAPHqxiKwxntXVkhgvik"
      role: admin
      
plugin_attr:
  jwt-auth:
    secret: "cbnaidsf9321"
    exp: 86400
 
plugins:
  - jwt-auth
  - cors
 
http:
  enable_access_log: true
  access_log: "/usr/local/apisix/logs/access.log"
  error_log: "/usr/local/apisix/logs/error.log"
 
routes:
  - uri: "/api/*"
    plugins:
      jwt-auth:
        header: "Authorization"
        query: "token"
    upstream:
      type: roundrobin
      nodes:
        "127.0.0.1:3000": 1
 
  - uri: "/api/v1/users/login"
    methods: ["POST"]
    upstream:
      type: roundrobin
      nodes:
        "127.0.0.1:3000": 1
 
  - uri: "/api/v1/users"
    methods: ["POST"]
    upstream:
      type: roundrobin
      nodes:
        "127.0.0.1:3000": 1
 
  - uri: "/api/v1/users"
    methods: ["GET", "DELETE"]
    plugins:
      jwt-auth:
        header: "Authorization"
        query: "token"
    upstream:
      type: roundrobin
      nodes:
        "127.0.0.1:3000": 1
 
  - uri: "/api/v1/functions"
    methods: ["POST", "GET", "DELETE"]
    plugins:
      jwt-auth:
        header: "Authorization"
        query: "token"
    upstream:
      type: roundrobin
      nodes:
        "127.0.0.1:3000": 1
