version: '3.9'

services:
  etcd:
    image: bitnami/etcd:latest
    container_name: etcd
    ports:
      - "2379:2379"
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ADVERTISE_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
    networks:
      - apisix-network

  apisix:
    image: apache/apisix:latest
    container_name: apisix
    depends_on:
      - etcd
    ports:
      - "9080:9080"
      - "9443:9443"
    volumes:
      - ./apisix_conf:/usr/local/apisix/conf
      - ./apisix_logs:/usr/local/apisix/logs
    networks:
      - apisix-network

networks:
  apisix-network:
    driver: bridge
