export class MessagingConfig {
  static readonly AWS_REGION = 'AWS_REGION';
  static readonly AWS_SQS_ENDPOINT = 'AWS_SQS_ENDPOINT';
  static readonly AWS_SNS_ENDPOINT = 'AWS_SNS_ENDPOINT';
  static readonly FUNCTION_DISPATCHING_QUEUE = "FUNCTION_DISPATCHING_QUEUE";
  static readonly FUNCTION_EXECUTION_TOPIC_PREFIX = "FUNCTION_EXECUTION_TOPIC_PREFIX";
}